### PR TITLE
M #-: Do a paranoid check to ignore services with LB class

### PR DESCRIPTION
**Pull request by sk4zuzu**

### CODE REVIEW

**Comment by aleixrm** [comment]
LGTM, and in the future maybe we can add some flag to force our controller to only listen on services with a specific load balancer class in case we find other controller that could cause conflicts and doesn't support that parameter (but maybe that doesn't make sense in our current ecosystem).

**Review by aleixrm — APPROVED** [review]

**Comment by sk4zuzu** [comment]
@aleixrm so this change is let's say "paranoid", in fact k8s does not notify the CP about services with LB class defined, so I believe to handle a custom lb class in the CP requires some extra work (it may be even impossible, not sure) :)

**Comment by aleixrm** [comment]
> @aleixrm so this change is let's say "paranoid", in fact k8s does not notify the CP about services with LB class defined, so I believe to handle a custom LB class in the CP requires some extra work (it may be even impossible, not sure) :trollface:

Ah okay, I misunderstood! I thought that you could check the LB class in the service object the controller received 😢 Thanks for clarifying!

**Comment by sk4zuzu** [comment]
> Ah okay, I misunderstood! I thought that you could check the LB class in the service object the controller received 😢 Thanks for clarifying!

Yes you can, we do that here, that doesn't mean though the controller-manager process will get this notification (and it currently doesn't), but this is enough for now, I believe. :+1: :innocent:

**Pull request merged**
